"""Add investments table

Revision ID: 17a334ec5813
Revises: b191ead44f29
Create Date: 2026-02-25 18:44:26.740290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a334ec5813'
down_revision = 'b191ead44f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=False))
        batch_op.alter_column('asset_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('current_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.alter_column('current_value',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('asset_name')

    # ### end Alembic commands ###
