"""Add quantity to investments

Revision ID: 643392a19660
Revises: 17a334ec5813
Create Date: 2026-02-26 02:52:52.631585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643392a19660'
down_revision = '17a334ec5813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
